# docker-compose.yml
services:
    app: &app-base
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: appointments_app
        container_name: appointments_app
        restart: unless-stopped
        working_dir: /var/www
        # inyectamos todo lo de .env en el contenedor
        env_file:
            - .env
        # montamos tu código
        volumes:
            - ./:/var/www
            - vendor-data:/var/www/vendor
        # Agregamos configuración para acceder al host
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - appnet
        depends_on:
            - db
            - redis
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "7"
        environment:
            - TZ=America/Bogota

    db:
        image: mysql:8.0
        container_name: appointments_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: appointments
            MYSQL_USER: appuser
            MYSQL_PASSWORD: apppass
            TZ: America/Bogota
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - appnet
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "7"

    redis:
        image: redis:7-alpine
        container_name: appointments_redis
        restart: unless-stopped
        volumes:
            - redisdata:/data
        networks:
            - appnet
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "7"
        environment:
            - TZ=America/Bogota

    nginx:
        image: nginx:stable-alpine
        container_name: appointments_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - appnet
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "7"
        environment:
            - TZ=America/Bogota

    horizon:
        <<: *app-base
        container_name: appointments_horizon
        restart: unless-stopped
        # inyectamos las mismas vars que en app
        env_file:
            - .env
        volumes:
            - ./:/var/www
            - vendor-data:/var/www/vendor
        # sobreescribimos solo el comando de arranque
        command: ["php", "artisan", "horizon"]
        # Agregamos configuración para acceder al host (heredado de app-base)
        depends_on:
            - redis
            - db
        networks:
            - appnet
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "7"
        environment:
            - TZ=America/Bogota

    ngrok:
        image: ngrok/ngrok:latest # entrypoint = "ngrok"
        container_name: appointments_ngrok
        restart: unless-stopped
        depends_on:
            - nginx
        environment:
            NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
            TZ: America/Bogota
        # ⬇️ El comando se pasa SIN repetir la palabra 'ngrok'
        command:
            - "http" # sub-comando
            - "nginx:80" # <host interno>:<puerto>
            - "--hostname=app.colibrixa.com"
            - "--log=stdout" # para ver la URL con docker logs
        ports:
            - "4040:4040"
        networks:
            - appnet
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "7"

    scheduler:
        <<: *app-base
        container_name: appointments_scheduler
        restart: unless-stopped
        command:
            [
                "sh",
                "-c",
                "while :; do php artisan schedule:run --verbose --no-interaction & sleep 60; done",
            ]
        volumes:
            - ./:/var/www
            - vendor-data:/var/www/vendor
        depends_on:
            - db
            - redis
        networks:
            - appnet
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "7"
        environment:
            - TZ=America/Bogota

volumes:
    dbdata:
    redisdata:
    vendor-data:

networks:
    appnet:
